baseurl = "http://liamjbennett.me/"
title = "Liam Bennett"
paginate = 5
theme = "hyde"
copyright = "Liam Bennett"

[Author]
  name = "Liam Bennett"

[Permalinks]
  blog = "/:year/:month/:filename/"
  code = "/:filename/"

[params]
  themeColor = "theme-base-0d"
  description = "Tools, Rants and Day-to-day Shenanigans"
  github = "liamjbennett"
  twitter = "liamjbennett"
