baseurl                 = "http://liamjbennett.me/"
DefaultContentLanguage  = "en"
title                   = "Liam Bennett"
theme                   = "hugo-future-imperfect-slim"
preserveTaxonomyNames   = true
paginate                = 5
disqusShortname         = ""
googleAnalytics         = ""
pluralizeListTitles     = false
disableLanguages        = ["fr","pl"]

[params]
  cssFiles              = ["default"]
  jsFiles               = ["default"]
  highlightjs           = true
  highlightjsTheme      = "github"
  highlightjsLang       = ["html", "css", "js", "toml"]
  viewMorePostsLink     = "/blog/"
  readingTime           = true
  socialShare           = ["twitter", "linkedin", "email"]

  [params.meta]
    description         = "Liam Bennett"
    author              = "Liam Bennett"
    favicon             = false
    svg                 = true
    faviconVersion      = "1"
    msColor             = "#ffffff" # Copy from the https://realfavicongenerator.net
    iOSColor            = "#ffffff" # Copy from the https://realfavicongenerator.net

  [params.header]
    navbarTitle         = "Liam Bennett"
    dynamicTitles       = true
    searchMenu          = true
    shareMenu           = true
    languageMenu        = false

  [params.intro]
    header                = "Liam Bennett"
    paragraph             = "tools, rants and day-to-day opinions"
    rssIntro              = true
    socialIntro           = true

    # This appears at the top of the sidebar above params.intro.header.
    # A width of less than 100px is recommended from a design perspective.
    [params.intro.pic]
      src                 = "/img/main/logo.jpg"
      # Masks image in a certain shape. Supported are circle, triangle, diamond, and hexagon.
      shape               = "circle"
      width               = ""
      alt                 = "Liam Bennett"

  [params.sidebar]
    about               = "about me text"
    postAmount          = 10
    categories          = true
    categoriesByCount   = true

  [params.footer]
    rssFooter           = true
    socialFooter        = true

[menu]
  [[menu.main]]
    name              = "Home"
    url               = "/"
    identifier        = "fas fa-home"
    weight            = 1

  [[menu.main]]
    name              = "About"
    url               = "/about/"
    identifier        = "far fa-id-card"
    weight            = 2

  [[menu.main]]
    name              = "Blog"
    url               = "/blog/"
    identifier        = "far fa-newspaper"
    weight            = 3

  [[menu.main]]
    name              = "Categories"
    url               = "/categories/"
    identifier        = "fas fa-sitemap"
    weight            = 5

[Languages]
  [Languages.en]
    languageCode        = "en"
    LanguageName        = "English"
    weight              = 1

[social]
  github                = "liamjbennett"
  gitlab                = ""
  stackoverflow         = "" # User Number
  linkedin              = "example"
  slideshare            = ""
  twitter               = "liamjbennett"
  email                 = "liamjbennett@gmail.com"