baseURL: "https://liamjbennett.me"
title: liamjbennett
paginate: 10
theme: hugo-PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true

googleAnalytics: G-DFMYZ5KKFV

minify:
    disableXML: true

languageCode: en-gb

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production
    description: ""
    author: liamjbennett

    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: true
    # disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: true
    # comments: false

    homeInfoParams:
        Title: "Hello!"
        Content: >
            Welcome to my site where I post my thoughts, my ideas and my general ramblings.
            I care about helping people and organisations get the most of technology.
            I am mostly interested in leading and growing engineering teams, aligning engineers with purpose and values and wardley mapping.
            I hope you find some of it useful.
            Please feel free to reach out to me at details below or check out the contacts page for other places I linger.

    socialIcons:
        - name: mastodon
          url: "https://hachyderm.io/@liamjbennett"
        - name: linkedin
          url: "https://www.linkedin.com/in/liam-bennett-77415821/"
        - name: email
          url: liamjbennett@gmail.com
        - name: RSS
          url: "index.xml"

menu:
  main:
    - identifier: about
      name: About Me
      url: /about/
      weight: 10
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 20
    - identifier: takes
      name: Takes
      url: /takes/
      weight: 30
    - identifier: cv
      name: Résumé
      url: /resume/
      weight: 40
    - identifier: contact
      name: Contact
      url: /contact/
      weight: 50

taxonomies:
    category: categories
    tag: tags
    series: series