baseURL: "https://www.liamjbennett.me"
title: liamjbennett
copyright: Copyright 2013-2024 Liam Bennett
pagination:
  pagerSize: 10
theme: hugo-PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true

googleAnalytics: G-DFMYZ5KKFV

ignoreLogs: ['warning-goldmark-raw-html']

minify:
    disableXML: true

languageCode: en-gb

outputs:
    home:
      - HTML
      - RSS
      - AUDIO
      - WEEKNOTES
      - DEVLOG

outputFormats:
  RSS:
    mediatype: application/rss
    baseName: feed
  AUDIO:
    mediatype: application/rss
    baseName: audio
  WEEKNOTES:
    mediatype: application/rss
    basename: weeknotes
  DEVLOG:
    mediatype: application/rss
    basename: devlog

params:
    env: production
    description: ""
    author: liamjbennett

    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: true
    # disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: true
    # comments: false
    social: true

    mainSections:
      - posts

    homeInfoParams:
        Title: "Hello!"
        Content: >
            Welcome to my site where I post my thoughts, my ideas and my general ramblings.
            I care about helping people and organisations get the most of technology.
            I am mostly interested in leading and growing engineering teams, aligning engineers with purpose and values and wardley mapping.
            I hope you find some of it useful.
            Please feel free to reach out to me at details below or check out the contacts page for other places I linger.

    socialIcons:
        - name: mastodon
          url: "https://hachyderm.io/@liamjbennett"
        - name: linkedin
          url: "https://www.linkedin.com/in/liam-bennett-77415821/"
        - name: email
          url: liamjbennett@gmail.com
        - name: rss
          url: "feed.xml"
        - name: rss
          url: "audio.xml"

menu:
  main:
    - identifier: about
      name: About Me
      url: /about/
      weight: 10
    - identifier: writing
      name: Writing
      url: /pages#writing
      weight: 20
    - identifier: now
      name: Now
      url: /now
      weight: 30
    - identifier: links
      name: Links
      url: /links
      weight: 40
    - identifier: pages
      name: Pages
      url: /pages/
      weight: 50

taxonomies:
    category: categories
    tag: tags
    series: series