baseURL: "https://liamjbennett.me"
title: liamjbennett
paginate: 10
theme: hugo-PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true

minify:
    disableXML: true

languages:
    en:
        languageName: "English"
        weight: 1

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production
    description: ""
    author: liamjbennett

    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: true
    # disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: true
    # comments: false
    images: ["papermod-cover.png"]

    homeInfoParams:
        Title: "Hello!"
        Content: >
            Welcome to my site where I post my thoughts, my ideas and my general ramblings.
            I care about helping people and organisations get the most of technology.
            I am mostly interested in leading and growing engineering teams, aligning engineers with purpose and values and wardley mapping.
            I hope you find some of it useful.

    socialIcons:
        - name: twitter
          url: "https://twitter.com/liamjbennett"
        - name: linkedin
          url: "https://www.linkedin.com/in/liam-bennett-77415821/"
        - name: github
          url: "https://github.com/liamjbennett"
        - name: RSS
          url: "index.xml"

taxonomies:
    category: categories
    tag: tags
    series: series