[build]
  command = """
    pip install vale &&
    vale sync &&
    vale content/weeknotes/ &&
    vale content/posts/ &&
    hugo
  """
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.161.1"

[[redirects]]
  from = "/blogroll"
  to = "/blogroll.xml"
  status = 301
  force = true

[[redirects]]
  from = "/podroll"
  to = "/podroll.xml"
  status = 301
  force = true

[[redirects]]
  from = "/posts/:slug/"
  to = "/posts/:year/:slug/"
  status = 301
  force = true